### ISSUE TITLE
Update/remove Item ID 1879335586 - superlative essence of morale

### ISSUE THREAD

**Issue by rujudan** [dmorcellet/lotro-companion#3]
the item no longer exists as of november 2016. please update or add to include Pelennor Essence of Morale, which has 1148 morale and 49 fate

**Comment by dmorcellet** [comment]
Ok, I checked that.
The Superlative has not been removed from the items database. May be it just does not drop any more.
The Pelennor Essence of Morale was skipped in the generation process because of a bug...
It will be fixed in the next release.
Thanks for this feedback.

**Comment by dmorcellet** [comment]
Commited the fixed items in project lotro-items-db.
Commited the essences generator in project lotro-tools
